env:
  browser: true
  es2021: true
  node: true
  jest: true
  cypress/globals: true
extends:
  - prettier/prettier
  - eslint:recommended
  - next/core-web-vitals
  - plugin:react/recommended
  - plugin:cypress/recommended
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
overrides: [ ]
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module
plugins:
  - react
  - cypress
  - prettier
  - '@typescript-eslint'
rules: {
  'prettier/prettier': [
      'error',
    {
      'endOfLine': 'auto',
    },
    {
      'usePrettierrc': true,
    },
  ],
  "cypress/no-force": "warn",
  "cypress/no-pause": "error",
  "cypress/no-async-tests": "error",
  "react/react-in-jsx-scope": "off",
  "import/no-anonymous-default-export": 0,
  "@typescript-eslint/no-var-requires": 0,
  "cypress/no-unnecessary-waiting": "error",
  "cypress/no-assigning-return-values": "error",
  "cypress/assertion-before-screenshot": "warn",
  "@typescript-eslint/no-non-null-assertion": "off",
  'react/no-children-prop': 'off',
}
settings:
  react:
    version: 'detect'
