version: 0.2

phases:
  install:
    commands:
      - bun install
  build:
    commands:
      - bun run build
  post_build:
    commands:
      - bun run export

artifacts:
  files:
    - '**/*'
  base-directory: 'out'