import { ReactNode } from 'react'

import { Analytics } from '@vercel/analytics/react'

import './globals.css'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: ReactNode }) => {
	return (
		<html lang='en'>
			<body>{children}</body>
			
			<Analytics />
		</html>
)
}

export default RootLayout
